=== radamhu/prog101/xml101/1 XML példák/receptek.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- elemek -->
<xs:element name="cim" type="xs:string"/>
<xs:element name="lepes" type="xs:string"/>

<!-- attribÃºtumok -->
<xs:attribute name="nev" type="xs:string"/>
<xs:attribute name="elk_ido" type="xs:string"/>
<xs:attribute name="sutes_ido" type="xs:string"/>
<xs:attribute name="mennyiseg" type="xs:decimal"/>
<xs:attribute name="egyseg" type="xs:string"/>

<!-- tartalom -->
<xs:element name="osszetevo">
<xs:complexType>
  <xs:simpleContent>
   <xs:extension base="xs:string">
    <xs:attribute ref="mennyiseg"/>
    <xs:attribute ref="egyseg"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
</xs:element>

<xs:element name="osszetevok">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="osszetevo"  maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="Utasitasok">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="lepes"  maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="Recept">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="cim" />
      <xs:element ref="osszetevok" />
      <xs:element ref="Utasitasok"/>
    </xs:sequence>
    <xs:attribute ref="nev" use="required"/>
    <xs:attribute ref="elk_ido" use="required"/>
    <xs:attribute ref="sutes_ido" use="required"/>
  </xs:complexType>
</xs:element>

<xs:element name="Receptek">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Recept" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== radamhu/prog101/xml101/1 XML példák/receptek.xml
<?xml version="1.0" encoding="UTF-8"?>
  <Receptek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="receptek.xsd">
  <Recept nev="kenyér" elk_ido="5 perc" sutes_ido="3 óra">
    <cim>Egyszerű kenyér</cim>
    <osszetevok>
      <osszetevo mennyiseg="3" egyseg="csésze">Liszt</osszetevo>
      <osszetevo mennyiseg="10" egyseg="dekagramm">Élesztő</osszetevo>
      <osszetevo mennyiseg="1.5" egyseg="csésze">Meleg víz</osszetevo>
      <osszetevo mennyiseg="1" egyseg="teáskanál">Só</osszetevo>
    </osszetevok>
    <Utasitasok>
      <lepes>Keverj össze minden összetevőt, aztán jól gyúrd össze!</lepes>
      <lepes>Fedd le ruhával és hagyd pihenni egy óráig egy meleg szobában!</lepes>
      <lepes>Gyúrd össze újra, helyezd bele egy bádogedénybe, aztán süsd meg a sütőben!</lepes>
    </Utasitasok>
  </Recept>
  <Recept nev="kifli" elk_ido="2 perc" sutes_ido="1 óra">
    <cim>Egyszerű kifli</cim>
    <osszetevok>
      <osszetevo mennyiseg="1" egyseg="csésze">Liszt</osszetevo>
      <osszetevo mennyiseg="3" egyseg="dekagramm">Élesztő</osszetevo>
      <osszetevo mennyiseg="0.5" egyseg="csésze">Meleg víz</osszetevo>
      <osszetevo mennyiseg="0.3" egyseg="teáskanál">Só</osszetevo>
    </osszetevok>
    <Utasitasok>
      <lepes>Keverj össze minden összetevőt, aztán jól gyúrd össze!</lepes>
      <lepes>Fedd le ruhával és hagyd pihenni fél óráig egy meleg szobában!</lepes>
      <lepes>Gyúrd össze újra, helyezd bele egy bádogedénybe, aztán süsd meg a sütőben!</lepes>
    </Utasitasok>
  </Recept>
</Receptek>
