=== radamhu/prog101/xml101/1 XML példák/tanulok.dtd
<!ELEMENT tanulók (tanuló)*>
<!ELEMENT tanuló (név,anyjaNeve,lakcím,telefon,email*)>
<!ELEMENT név (#PCDATA)>
<!ELEMENT anyjaNeve (#PCDATA)>
<!ELEMENT lakcím (irsz,város,utca,házSzám)>
<!ELEMENT irsz (#PCDATA)>
<!ELEMENT város (#PCDATA)>
<!ELEMENT utca (#PCDATA)>
<!ELEMENT házSzám (#PCDATA)>
<!ELEMENT telefon (otthoni?,mobil*)>
<!ELEMENT otthoni (#PCDATA)>
<!ELEMENT mobil (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== radamhu/prog101/xml101/1 XML példák/tanulok.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tanulók SYSTEM "tanulok.dtd">
<tanulók>
	<tanuló>
		<név>Gipsz Jakab</név>
		<anyjaNeve>Gipsz Juli</anyjaNeve>
		<lakcím>
			<irsz>1234</irsz>
			<város>Budapest</város>
			<utca>Kossuth</utca>
			<házSzám>5</házSzám>
		</lakcím>
		<telefon>
			<otthoni>43243243</otthoni>
			<mobil>43243243</mobil>
		</telefon>
		<email>jani@gipsz.hu</email>
	</tanuló>
</tanulók>
